### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by intulint** [keldenl/gpt-llama.cpp#18]
I run it on ubuntu and it cursed until I changed the port, set it to 4000.
But at startup everything that is written on the page "Canot GET /" on white fone.
Firefox browser

**Comment by keldenl** [comment]
`localhost:4000` doesn't take your anywhere, `localhost:4000/docs` will take you to the docs. let me improve the messaging of the app. lmk if /docs works!

**Comment by keldenl** [comment]
just pushed a change, now visiting localhost:4000  returns something descriptive (instead of cannot GET /) 

and the "server running" message in terminal/cmd should be more descriptive now

hopefully this helps avoid confusion for folks like u trying to setup for the first time! (commit: https://github.com/keldenl/gpt-llama.cpp/commit/50d06cdaed6fc19da924775d0108dd892674f370)

**Comment by intulint** [comment]
Oh, I already figured it out, I just didn't launch it that way. I looked at your docks on auto-gpt. But a stub for people like me is a useful thing, thanks
