### ISSUE TITLE
Duplication of capabilities?

### ISSUE THREAD

**Issue by das-sein** [keldenl/gpt-llama.cpp#34]
Filing this issue primarily to make the developers aware of the existing llama-cpp-python web server that accomplishes the same thing and also has endpoint documentation with examples baked in:

https://abetlen.github.io/llama-cpp-python/#web-server

![image](https://user-images.githubusercontent.com/6910190/235168401-fdfdfb3f-f1f6-47b4-97a8-9a27e6923601.png)

Hopefully this is useful or could reduce future development efforts in the attempt to address some of the other issues I'm seeing that request support for other popular open LLMs.

**Comment by keldenl** [comment]
Yes, but I had some issues with `llama.cpp-python`, which is why. I made `gpt-llama.cpp`. Also, `gpt-llama.cpp` is more lightweight because it just utilizes what the user has locally for their `llama.cpp` project, so getting any new changes and improvements (like the recent CUDA and 5-bit support) as easy as updating the `llama.cpp` project! `gpt-llama.cpp` doesn't have to do anything :)
